app:
  name: "Doclingflow"
  version: "0.1.0"
  debug: true

processing:
  # Watch folders for automatic processing
  watch_folders:
    - "/data/inbox"

  # Chunk settings for document splitting
  chunk_size: 1000
  chunk_overlap: 200

  # Processing settings
  max_concurrent_jobs: 2
  auto_process: true

  # File types to process
  supported_formats:
    - "pdf"
    - "docx"
    - "xlsx"
    - "pptx"
    - "txt"
    - "html"

# Document classification categories
classification:
  categories:
    - name: "Safety Data Sheets"
      keywords: ["sds", "msds", "safety", "hazard"]
    - name: "Technical Specifications"
      keywords: ["specification", "datasheet", "technical"]
    - name: "Equipment Manuals"
      keywords: ["manual", "maintenance", "operation"]
    - name: "Business Documents"
      keywords: ["invoice", "contract", "agreement", "report"]
    - name: "Regulatory Compliance"
      keywords: ["compliance", "regulation", "permit", "certificate"]
    - name: "Operational Procedures"
      keywords: ["procedure", "sop", "standard operating"]

# LLM Configuration
llm:
  provider: "openrouter"  # openrouter (preferred), openai, anthropic, or ollama
  model: "anthropic/claude-3.5-sonnet"  # Claude via OpenRouter
  temperature: 0.1
  max_tokens: 2000

  # OpenRouter settings (preferred)
  openrouter_api_key: ${OPENROUTER_API_KEY}
  openrouter_base_url: ${OPENROUTER_BASE_URL}

  # Alternative models via OpenRouter:
  # - anthropic/claude-3.5-sonnet (recommended)
  # - anthropic/claude-3-opus
  # - anthropic/claude-3-haiku

  # Ollama settings (if using local models)
  ollama_base_url: "http://localhost:11434"
  ollama_model: "llama2"

# Embedding configuration
embeddings:
  provider: "openrouter"  # openrouter (preferred) or sentence-transformers
  model: "openai/text-embedding-3-small"  # Via OpenRouter
  dimensions: 1536

  # Alternative: local embeddings
  # provider: "sentence-transformers"
  # model: "all-MiniLM-L6-v2"
  # dimensions: 384

# Vector database
qdrant:
  collection_name: "documents"
  distance_metric: "Cosine"

# Metadata extraction
entity_extraction:
  enabled: true
  extract:
    - "equipment_ids"
    - "chemical_names"
    - "dates"
    - "locations"
    - "personnel"
    - "measurements"

# Storage
storage:
  inbox_path: "/data/inbox"
  processed_path: "/data/processed"
  failed_path: "/data/failed"
  archive_path: "/data/archive"

  # Archive settings
  archive_after_days: 30
  delete_after_days: 90
